files:
  - tag: abc
    path: locallog.txt
destination:
  host: 127.0.0.1
  port: 514
  protocol: udp
exclude_patterns:
  - don't log on me
# 可以是下列值中任意一个： emerg,alert,crit,err,warn,notice,info,debug
severity: alert
# 可以是下列值中任意一个： kern,user,mail,daemon,auth,syslog,lpr,news,uucp,cron,authpriv,ftp,ntp,audit,alert,at,local0,local1~7
facility: kern